import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Hero from "../components/Hero/Hero";
import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <h2>This is main</h2>
        <Link href="/about">Click Me</Link>
      </main>
      <Footer />
    </div>
  );
}
